### ISSUE TITLE
binary imp -i fails w/ keyerror

### ISSUE THREAD

**Issue by theAeon** [arkane-systems/bottle-imp#3]
running opensuse tumbleweed compiled binary directly on latest wsl2.

unsure what to do here-i don't know why there would be an IMP_LOGNAME present for initiation. Is this something set at package installation?

```
andrew@Andrew-Ryzen:~> sudo bottle-imp/binsrc/out/imp -i
Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/andrew/bottle-imp/binsrc/out/imp/__main__.py", line 197, in <module>
  File "/home/andrew/bottle-imp/binsrc/out/imp/__main__.py", line 166, in entrypoint
  File "/home/andrew/bottle-imp/binsrc/out/imp/helpers.py", line 12, in get_login_session_user
  File "/usr/lib64/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
```

**Comment by cerebrate** [comment]
There are actually two chained executables, because _imp_ needs to run setuid and python scripts can't run setuid. The executable generated by _imp-wrapper_ (which you'll find in its directory, rather than out) is installed setuid as _/usr/bin/imp_, and when executed, sets the original user name into the IMP_LOGNAME variable to pass it through, then execs _/usr/lib/bottle-imp/imp_ (the path is hard-coded in _imp.c_), the executable you're trying to run.

**Comment by theAeon** [comment]
guess the best way to make this happen would be to add a make install routine, no?

**Comment by cerebrate** [comment]
0.4 (which you can grab from the dev branch) includes an option to make an installable tarball.

**Comment by theAeon** [comment]
Looking good,

Apparently my tar doesn't preserve setuid bit, which, well not your problem but certainly interesting. I checked the archive and the setuid bit is there.
